---
title: "Deliverable2TheAnchors"
author: "Anchors"
date: "2023-02-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
JoinEcon = read.csv("economy.csv")

JoinDF = as.data.frame(JoinEcon)
```

```{r}
str(JoinDF)
```

```{r}

dataToFactor = JoinDF[,-c(1,2)]

str(dataToFactor)
```

```{r}
library(polycor)
JoinMatrix=polycor::hetcor(dataToFactor)$correlations
```

```{r}
library(ggcorrplot)

ggcorrplot(JoinMatrix,
           type = "lower") + 
          theme(axis.text.x  = element_text(size = 5),
                axis.text.y  = element_text(size = 5))
```

```{r}
library(psych)
psych::KMO(JoinMatrix) 
```
```{r}
# is this an identity matrix? shouldn't be . . .
cortest.bartlett(JoinMatrix,n=nrow(dataToFactor))$p.value>0.05
```
```{r}
# is the matrix singular? shouldn't be . . .
library(matrixcalc)
```


```{r}
is.singular.matrix(JoinMatrix)
```
aw beans

```{r}
fa.parallel(dataToFactor, fa = 'fa',correct = T,plot = F)
```
```{r}
library(GPArotation)
resfa <- fa(dataToFactor,
            nfactors = 2,
            cor = 'mixed',
            rotate = "varimax",
            fm="minres")
```
```{r}
print(resfa$loadings,cutoff = 0.5)
```
```{r}
fa.diagram(resfa,main = "EFA results")
```
```{r}
newData=c("Energy consumption","Carbon dioxide emissions","Revenue from coal")
removedData=setdiff(names(dataToFactor),newData)
dataToFactor2=dataToFactor[,removedData]
```

```{r}
library(polycor)
corMatrix2=polycor::hetcor(dataToFactor2)$correlations
```

```{r}
library(psych)
psych::KMO(corMatrix2) 
```
```{r}
cortest.bartlett(corMatrix2,n=nrow(dataToFactor2))$p.value>0.05
```

```{r}
library(matrixcalc)

is.singular.matrix(corMatrix2)
```
```{r}
fa.parallel(dataToFactor2, fa = 'fa',correct = T,plot = F)
```
```{r}

regdata=dataToFactor2
str(regdata,width=70,strict.width='cut')
hypo1=formula(Energy.consumption~ Oil.imports)
hypo2=formula(Energy.consumption~ Oil.imports + Carbon.dioxide.emissions)
hypo3=formula(Energy.consumption~ Oil.imports + Carbon.dioxide.emissions + Industrial.production.growth.rate)
```


```{r}
gauss1=glm(hypo1,
           data = regdata,
           family = 'gaussian')

gauss2=glm(hypo2,
           data = regdata,
           family = 'gaussian')

gauss3=glm(hypo3,
           data = regdata,
           family = 'gaussian')
```


```{r}
summary(gauss1)
summary(gauss2)
summary(gauss3)
```


```{r}
library(rsq)
rsq(gauss1,adj=T); rsq(gauss2,adj=T); rsq(gauss3,adj=T)
```
```{r}
anova(gauss1,gauss2,gauss3,test="Chisq")
```
```{r}
#model 3 is the preferred.
plot(gauss3,1)

```
```{r}
#Visual exploration
plot(gauss3,2)
```
```{r}
shapiro.test(gauss3$residuals)
```
```{r}
plot(gauss3, 3)
```
```{r}
#Interpretting the results.

```

